/*
 * Generated by tools/design.py. Do not edit by hand; edit the
 * script and run it again.
 */

#ifndef INC_KERNELS_H_
#define INC_KERNELS_H_

#include "arm_math.h"

#define MA_11_LEN       11
#define LP_RECT_LEN     101
#define LP_HAMMING_LEN  101
#define LP_BLACKMAN_LEN 101
#define LP_31_LEN       31
#define LP_201_LEN      201
#define LP_50_LEN       101
#define BP_50_300_LEN   101
#define HP_300_LEN      101

extern const float32_t ma_11[MA_11_LEN];
extern const float32_t lp_rect[LP_RECT_LEN];
extern const float32_t lp_hamming[LP_HAMMING_LEN];
extern const float32_t lp_blackman[LP_BLACKMAN_LEN];
extern const float32_t lp_31[LP_31_LEN];
extern const float32_t lp_201[LP_201_LEN];
extern const float32_t lp_50[LP_50_LEN];
extern const float32_t bp_50_300[BP_50_300_LEN];
extern const float32_t hp_300[HP_300_LEN];

#endif /* INC_KERNELS_H_ */
