/*
 * Generated by tools/design.py. Do not edit by hand; edit the
 * script and run it again.
 */

#ifndef INC_TESTSIG_H_
#define INC_TESTSIG_H_

#include "arm_math.h"

#define TESTSIG_FS_HZ   2000U
#define SIG_LEN         200
#define NOISE_LEN       600
#define REF_LP50_LEN    300

extern const float32_t sig_3tone[SIG_LEN];
extern const float32_t tone_10[SIG_LEN];
extern const float32_t tone_100[SIG_LEN];
extern const float32_t tone_500[SIG_LEN];
extern const float32_t sig_noisy[NOISE_LEN];
extern const float32_t ref_lp50[REF_LP50_LEN];

#endif /* INC_TESTSIG_H_ */
